//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Showcase {
	
	
	public partial class index {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.HyperLink lnkLogin;
		
		protected System.Web.UI.WebControls.HyperLink lnkSignup;
		
		protected System.Web.UI.WebControls.HyperLink lnkEditar;
		
		protected System.Web.UI.WebControls.HyperLink lnkRecargar;
		
		protected System.Web.UI.WebControls.HyperLink lnkLogout;
		
		protected System.Web.UI.WebControls.HyperLink lnkLoginStatus;
		
		protected System.Web.UI.WebControls.HyperLink lnkUserLoged;
		
		protected System.Web.UI.WebControls.HyperLink lnkRefreshToken;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl html_info;
	}
}
